### ISSUE TITLE
Sync photo album

### ISSUE THREAD

**Issue by alvesjtiago** [recall-photos/recall-ios#5]
Automatically back-up all photos from the device to Recall.

- [ ] Background upload - https://github.com/recall-photos/recall-ios/issues/6
- [ ] Background upload indicator - https://github.com/recall-photos/recall-ios/issues/7
- [ ] Prompt backup - https://github.com/recall-photos/recall-ios/issues/8
- [ ] Backup process - https://github.com/recall-photos/recall-ios/issues/9
